# Generated by Django 4.0.4 on 2022-08-27 05:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '01XXXNNNNNN' in 11 digits.", regex='^01?\\d{9}$')], verbose_name='mobile number'),
        ),
    ]
