# Generated by Django 4.0.4 on 2022-08-08 07:55

import banking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_alter_account_account_no_alter_account_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='id',
        ),
        migrations.AlterField(
            model_name='account',
            name='account_no',
            field=models.CharField(default=banking.models.generate_pk, max_length=16, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(default=banking.models.generate_pk, max_length=16, primary_key=True, serialize=False, unique=True),
        ),
    ]
