# Generated by Django 4.0.4 on 2022-08-08 08:02

import banking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0004_remove_account_id_alter_account_account_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(default=banking.models.generate_trnx, max_length=24, primary_key=True, serialize=False, unique=True),
        ),
    ]
