# Generated by Django 4.0.4 on 2022-08-09 10:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0005_alter_transaction_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='pin',
            field=models.PositiveIntegerField(default=12345, validators=[django.core.validators.MinValueValidator(10000), django.core.validators.MaxValueValidator(99999)]),
        ),
    ]
