# Generated by Django 4.0.4 on 2022-08-09 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0009_alter_transaction_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='shared_accounts',
            field=models.ManyToManyField(blank=True, null=True, related_name='shared_transactions', to='banking.account'),
        ),
    ]
