# Generated by Django 4.0.4 on 2022-08-27 05:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0011_alter_transaction_shared_accounts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='pin',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='shared_accounts',
        ),
        migrations.AddField(
            model_name='transaction',
            name='cbc_beneficiary_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cbc_beneficiary', to='banking.account'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='cbc_beneficiary_phone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '01XXXNNNNNN' in 11 digits.", regex='^01?\\d{9}$')], verbose_name='mobile number'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='otp',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(999999)]),
        ),
    ]
